[package]
name = "pokebell"
version = "0.1.0"
authors = ["yosh <garlic.ba.0129@gmail.com>"]
edition = "2018"

[lib]
name = "pokebell"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
failure = "0.1.7"
